const chalk = require('chalk');

module.exports = {
    LANG: 'zh_CN',
    WELECOME: `欢迎使用`,
    SHOW_VERSION: '查看当前版本',
    NO_COMMAND: '命令不存在',
    GREETING_GUIDE: '开始新建一个项目',
    NETWORK_DISCONNECT: '创建工程需要下载云端模版',
    NETWORK_DISCONNECT_SUG: '请确认您的设备处于网络可访问的环境中',
    LOADING_FROM_CLOUD: '正在拉取云端数据，请稍候',
    INPUT_INVALID: '输入不符合规范',
    PLEASE_INPUT: '请输入',
    PLEASE_INPUT_NUM_DESC: '请选择一个数字指定',
    PLEASE_INPUT_NUM: '请输入数字',
    PLEASE_INPUT_RIGHR_NUM: '请输入正确的数字',
    PLEASE_SELECT: '请选择一个',
    PLEASE_SELECT_DESC: '按上下键选择',
    META_TEMPLATE_ERROR: '获取模版 Meta 信息出错',
    DOWNLOAD_TEMPLATE_ERROR: '下载模版出错，请检查当前网络',
    LOADING_EXPORT_PROJECT: '正在导出工程',
    RENDER_TEMPLATE_ERROR: '模板渲染出错',
    INIT_SUCCESS: '项目已创建成功',
    INIT_NEXT_GUIDE: '您可以操作如下命令快速开始开发工程',
};
